-- Включаем Row Level Security на всех публичных таблицах.
-- Прод-приложение работает через Supabase pooler с пользователем `postgres`,
-- который BYPASS RLS, поэтому функциональность не затрагивается.
-- Без явных policies — anon/authenticated роли (PostgREST) лишаются доступа.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlayerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamJoinRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LfgPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tournament" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Match" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchPlayerStat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchResultClaim" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Season" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MvpAward" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Friendship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Sponsor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentSponsor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SponsorshipInquiry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "News" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorldNews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminActionLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
